# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23c0e67d3efbe838509a6c473413e8bf1328895a4bf1436c8c2b4de1b6246cd6d9fb85694c28702ee292a6e182e85566a6fdd8b94ecccdadc9c6c4ae15ba2828

test:
  secret_key_base: 89c4c34b8cc727b079a24097ddc35c6aa324645eb514a10002726be5f796aeb95f16184bad4978db6701d93ceb11e9437bbbe3929de0517f3ce303387de0a0c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
